# Generated by Django 3.2.10 on 2022-03-09 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('prof', models.PositiveIntegerField(choices=[(None, 'Выберите один из пунктов списка'), (7, 'Автомобильный бизнес'), (4, 'Административный персонал'), (5, 'Банки, инвестиции, лизинг'), (8, 'Безопасность'), (2, 'Бухгалтерия, управленческий учет, финансы предприятия'), (16, 'Государственная служба'), (9, 'Высший менеджмент'), (10, 'Добыча сырья'), (26, 'Закупки'), (27, 'Домашний персонал'), (25, 'Инсталляция и сервис'), (1, 'Информационные технологии, интернет, телеком'), (11, 'Искусство, развлечения, масс-медиа'), (12, 'Консультирование'), (3, 'Маркетинг, реклама, PR'), (13, 'Медицина, фармацевтика'), (14, 'Наука, образование'), (15, 'Начало карьеры, студенты'), (17, 'Продажи'), (18, 'Производство, сельское хозяйство'), (29, 'Рабочий персонал'), (24, 'Спортивные клубы, фитнес, салоны красоты'), (19, 'Страхование'), (20, 'Строительство, недвижимость'), (21, 'Транспорт, логистика'), (22, 'Туризм, гостиницы, рестораны'), (6, 'Управление персоналом, тренинги'), (23, 'Юристы'), (16, 'Государственная служба, некоммерческие организации')], verbose_name='Профессия')),
                ('status', models.IntegerField(blank=True, default=2, null=True)),
                ('dtcreate', models.DateTimeField(auto_now_add=True, db_column='dtCreate')),
                ('dtexec', models.DateTimeField(auto_now=True, db_column='dtExec', null=True)),
                ('cntres', models.IntegerField(blank=True, db_column='cntRes', null=True)),
                ('delete', models.BooleanField(default=True)),
                ('usr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'queries',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuerySearch',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='children', serialize=False, to='HH.queries')),
                ('text', models.TextField(verbose_name='Введите ключевые слова')),
                ('salary_to', models.IntegerField(blank=True, null=True, verbose_name='Введите предельную зп')),
                ('area', models.TextField(blank=True, null=True, verbose_name='Регион')),
                ('experience', models.CharField(blank=True, choices=[(None, 'Выберите один из пунктов списка'), ('нет', 'нет'), ('от 1 до 3', 'от 1 до 3'), ('от 3 до 6', 'от 3 до 6'), ('от 6', 'от 6')], max_length=300, verbose_name='Требуемый опыт работы')),
                ('skill', models.TextField(blank=True, null=True, verbose_name='Ключевые навыки (через ;)')),
                ('education', models.CharField(blank=True, choices=[(None, 'Выберите один из пунктов списка'), ('не имеет значения', 'не имеет значения'), ('Высшее', 'Высшее'), ('Бакалавр', 'Бакалавр'), ('Магистр', 'Магистр'), ('Кандидат наук', 'Кандидат наук'), ('Доктор наук', 'Доктор наук'), ('Незаконченное высшее', 'Незаконченное высшее'), ('Среднее', 'Среднее'), ('Среднее специальное', 'Среднее специальное')], max_length=300, null=True, verbose_name='Образование')),
                ('citizenship', models.TextField(blank=True, null=True, verbose_name='Гражданство')),
                ('work_ticket', models.TextField(blank=True, null=True, verbose_name='Разрешение на работу')),
                ('age_from', models.TextField(blank=True, null=True, verbose_name='Возраст (от)')),
                ('age_to', models.TextField(blank=True, null=True, verbose_name='Возраст (до)')),
                ('gender', models.CharField(blank=True, choices=[(None, 'Выберите один из пунктов списка'), ('не имеет значения', 'не имеет значения'), ('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=300, null=True, verbose_name='Пол')),
                ('employment_full', models.BooleanField(blank=True, null=True, verbose_name='Полная занятость')),
                ('employment_part', models.BooleanField(blank=True, null=True, verbose_name='Частичная занятость')),
                ('employment_project', models.BooleanField(blank=True, null=True, verbose_name='Проектная дестельность')),
                ('employment_volunteer', models.BooleanField(blank=True, null=True, verbose_name='Волонтёрство')),
                ('employment_probation', models.BooleanField(blank=True, null=True, verbose_name='Стажировка')),
                ('schedule_fullday', models.BooleanField(blank=True, db_column='schedule_fullDay', null=True, verbose_name='Полный день')),
                ('schedule_shift', models.BooleanField(blank=True, null=True, verbose_name='Сменный график')),
                ('schedule_flexible', models.BooleanField(blank=True, null=True, verbose_name='Гибкий график')),
                ('schedule_remote', models.BooleanField(blank=True, null=True, verbose_name='Удаленная работа')),
                ('schedule_flyinflyout', models.BooleanField(blank=True, db_column='schedule_flyInFlyOut', null=True, verbose_name='Вахтовый метод')),
                ('language', models.TextField(blank=True, null=True, verbose_name='Язык')),
                ('level', models.CharField(blank=True, choices=[(None, 'Выберите один из пунктов списка'), ('не имеет значения', 'не имеет значения'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B2'), ('C1', 'C2'), ('Родной', 'Родной')], max_length=300, null=True, verbose_name='Уровень владения')),
                ('searchurl', models.TextField(blank=True, db_column='searchURL', null=True)),
            ],
            options={
                'db_table': 'query_search',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('isneedcontact', models.BooleanField(blank=True, db_column='isNeedContact', null=True)),
                ('isdowncontact', models.BooleanField(blank=True, db_column='isDownContact', null=True)),
                ('idq', models.ForeignKey(db_column='idQ', on_delete=django.db.models.deletion.DO_NOTHING, to='HH.querysearch')),
            ],
            options={
                'db_table': 'urls',
                'managed': True,
            },
        ),
    ]
