# Generated by Django 5.0.1 on 2024-02-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HH', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='urls',
            name='last_job',
            field=models.TextField(blank=True, null=True, verbose_name='Последнее место работы'),
        ),
        migrations.AddField(
            model_name='urls',
            name='old',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='urls',
            name='salary_goal',
            field=models.TextField(blank=True, null=True, verbose_name='Зарплатные ожидания'),
        ),
        migrations.AddField(
            model_name='urls',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='queries',
            name='status',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='querysearch',
            name='text',
            field=models.TextField(verbose_name='Введите ключевые слова (через ;)'),
        ),
        migrations.AlterField(
            model_name='urls',
            name='isdowncontact',
            field=models.BooleanField(db_column='isDownContact', default=0),
        ),
        migrations.AlterField(
            model_name='urls',
            name='isneedcontact',
            field=models.BooleanField(db_column='isNeedContact', default=0),
        ),
    ]
