# Generated by Django 5.0.2 on 2024-02-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FOMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
