# Generated by Django 5.0.2 on 2024-02-08 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FOMS', '0002_file_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='ArchviedFiles',
        ),
    ]
